language: ruby
rvm:
- 2.5
sudo: false
install: gem install github-pages jekyll-liquify
script: jekyll build
branches:
  only:
  - master
env:
  global:
    secure: ohaYE4nccqxXRU9akcGV3+M13m0/2NhCMTbt9PPubomICL1cQcdLpvCYfTKq8tuuQ/DN8VY6t//4ZVYkugWijB6XyJGDfTSw6GAtZsc7AnxQheiH8MDQ3C9KsIIlMn9TrRqgR75lt/Cq3GyT5mYthbaXGetR0NlfVT7BKHOkQo1Gvh/7bPGrH2wUDrfs/fEVe9zuRJGuc0Qy/lf22WCihd57lSBcZ0ApeZjtaPVOi451teJKvZnwRHE/BrFVgdgteqQ8SiLC0Nr3DpPzUtx8H9Ejm7fPu8LiO1sFjpPY+6CCebpZl9ezys5X7MyZ1a9FlWrEj4xLDkBWvGdzrBA43LjHH34PJJ+p+AX3RruVIW6nx230IZOL3FK9yPgWIixJuqMkgj1w7DwSn4HulB2ZxFRHI63LgR2I+mz9ChFyv0N8h+2Ncpa9M61V8+30IoiN7A7d4kg1VuEXlcFPMjZp90c2dtcHMUJwNcsXelV7vZh7mJT3MGwEdtHZ3Z//We7BN2wkrXPskzF1DMRU7s/6GmnfLLfj04S6b47jOVxf5z78e2R+A23kXWAB6owpnVYHBwO6AwWdAx+/k6YkMeWMvpcgQAqaTqvwTL2MSrgyOmdlW1bmpomUKgbpVLQKvkFbgHarnF9qkicEx9AEd8zCq0n6kp61JpHWtuAs7WsTfMQ=
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
